# Run settings

run_name: "70B_therapist"

log_to_wandb: true

# Specify settings for generating trajectories
env_class: "test"
env_fractions: 
  vuln: 1
  normal: 0
envs: null
max_turns: 1

num_envs_per_device: 8 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
n_subenvs_to_sample_per_env: 4
subenv_choice_scheme: "sequential"
final_reward: false
scratchpad: false
traj_selection_level: "env"

# Trajectory generation settings
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/2
iterations: 10
pm_length_penalty: null

# Veto settings
veto_level: null # (no veto)
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
veto_prompt_type: "normal"
inference_quantization: "4-bit"

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3.1-70B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "env-veto|agent"

# Accelerate config type
accelerate_config_type: "DeepSpeed3"


# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
effective_batch_size: 16 # Number of steps to accumulate gradients before performing an update.
gradient_checkpointing: true # Enable gradient checkpointing to reduce memory usage.
learning_rate: 2e-6
across_iter_lr_mult_factor: 0.9
report_to: "none" # Disable reporting to any external service.
optim: "adamw_bnb_8bit"
max_length: 2048 # Maximum sequence length for input data.
lr_scheduler_type: "constant"
logging_steps: 1
max_grad_norm: 1.0

# LoRA hyperparameters
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 1024
max_completion_length: 1024

# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null
